version: "3.2"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  boilerplate:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres:
