version: "3.2"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  lookbook:
    build: .
    env_file:
      - .env
    ports:
      - "3432:3432"
    depends_on:
      - postgres
volumes:
  postgres:
